import { jsPDF } from 'jspdf';
import { Profile, Proof } from '../types';

export const exportPortfolioToPDF = (profile: Profile, proofs: Proof[]) => {
  const doc = new jsPDF();
  const margin = 20;
  let yPos = margin;

  // Header - Profile Info
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(profile.name || 'Anonymous Builder', margin, yPos);
  yPos += 10;

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(`@${profile.username || 'username'} | ${profile.focus}`, margin, yPos);
  yPos += 15;

  doc.setFontSize(12);
  doc.setTextColor(0);
  const bioLines = doc.splitTextToSize(profile.bio || 'No bio provided.', 170);
  doc.text(bioLines, margin, yPos);
  yPos += (bioLines.length * 7) + 15;

  // Divider
  doc.setDrawColor(200);
  doc.line(margin, yPos - 5, 190, yPos - 5);

  // Sections: All Proof Timeline
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Proof Timeline', margin, yPos);
  yPos += 10;

  if (proofs.length === 0) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'italic');
    doc.text('No proofs documented yet.', margin, yPos);
  } else {
    proofs.forEach((proof) => {
      // Check for page break
      if (yPos > 250) {
        doc.addPage();
        yPos = margin;
      }

      // Category Badge
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(106, 13, 173); // Primary color
      doc.text(proof.category.toUpperCase(), margin, yPos);
      yPos += 5;

      // Title
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0);
      doc.text(proof.title, margin, yPos);
      yPos += 7;

      // Date
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(150);
      doc.text(new Date(proof.timestamp).toLocaleDateString(), margin, yPos);
      yPos += 6;

      // Description
      doc.setFontSize(11);
      doc.setTextColor(50);
      const descLines = doc.splitTextToSize(proof.description, 170);
      doc.text(descLines, margin, yPos);
      yPos += (descLines.length * 6) + 5;

      // Link if exists
      if (proof.link) {
        doc.setFontSize(10);
        doc.setTextColor(30, 144, 255); // Secondary color
        doc.text(`Link: ${proof.link}`, margin, yPos);
        yPos += 7;
      }

      yPos += 10; // Spacing between items
    });
  }

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150);
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.text(`Generated by ProofSpace - Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
  }

  doc.save(`${profile.username || 'portfolio'}_proofspace.pdf`);
};
